// Módulo de fundaciones con sus características
export const FOUNDATIONS = [
  {
    id: "fundacion-di",
    name: "FUNDACIÓN DI",
    code: "145455",
    address: "SAN PEDRO DE",
    province: "GUAYAS",
    city: "GUAYAQUIL",
    canton: "GUAYAQUIL",
    parroquia: "CHONGON B",
    institution: "Ministerio de Inc",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["costa"],
    climateFocus: ["calor", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en GUAYAS, GUAYAQUIL que ayuda a la comunidad en zonas de costa",
  },
  {
    id: "fundacion-gf",
    name: "FUNDACIÓN GF",
    code: "145454",
    address: "Calles Bolivar S.",
    province: "PASTAZA",
    city: "PUYO",
    canton: "Puyo",
    parroquia: "",
    institution: "Ministerio del Ar",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["oriente"],
    climateFocus: ["calor", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en PASTAZA, PUYO que ayuda a la comunidad en zonas de oriente",
  },
  {
    id: "fundacion-to",
    name: "FUNDACION TO",
    code: "145453",
    address: "COOP. UNIDOS",
    province: "GUAYAS",
    city: "GUAYAQUIL",
    canton: "TARQUI",
    parroquia: "",
    institution: "Ministerio de Inc",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["costa"],
    climateFocus: ["calor", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en GUAYAS, GUAYAQUIL que ayuda a la comunidad en zonas de costa",
  },
  {
    id: "fundacion-pa",
    name: "FUNDACIÓN PA",
    code: "145451",
    address: "Avenida Coruña",
    province: "PICHINCHA",
    city: "QUITO",
    canton: "MARISCAL SUCRE",
    parroquia: "",
    institution: "Ministerio del Ar",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["sierra"],
    climateFocus: ["frio", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en PICHINCHA, QUITO que ayuda a la comunidad en zonas de sierra",
  },
  {
    id: "fundacion-ri",
    name: "FUNDACIÓN RI",
    code: "145449",
    address: "Avenida 12 de (",
    province: "PICHINCHA",
    city: "QUITO",
    canton: "",
    parroquia: "IÑAQUITO",
    institution: "Ministerio del Ar",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["sierra"],
    climateFocus: ["frio", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en PICHINCHA, QUITO que ayuda a la comunidad en zonas de sierra",
  },
  {
    id: "fundacion-ni",
    name: "FUNDACIÓN NI",
    code: "145447",
    address: "Vía Mercedes L",
    province: "PICHINCHA",
    city: "SAN MIGUEL DE LOS BANCOS",
    canton: "SAN MIGUEL D",
    parroquia: "",
    institution: "Ministerio del Ar",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["sierra"],
    climateFocus: ["frio", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en PICHINCHA, SAN MIGUEL DE LOS BANCOS que ayuda a la comunidad en zonas de sierra",
  },
  {
    id: "fundacion-ca",
    name: "FUNDACION CA",
    code: "145446",
    address: "Padre Rumi s/n",
    province: "PICHINCHA",
    city: "QUITO",
    canton: "SAN ANTONIO",
    parroquia: "",
    institution: "Ministerio de Inc",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["sierra"],
    climateFocus: ["frio", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en PICHINCHA, QUITO que ayuda a la comunidad en zonas de sierra",
  },
  {
    id: "fundacion-an",
    name: "FUNDACIÓN AN",
    code: "145445",
    address: "ELOY MUECKA",
    province: "LOS RIOS",
    city: "QUEVEDO",
    canton: "GUAYACÁN",
    parroquia: "",
    institution: "Ministerio de Inc",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["costa"],
    climateFocus: ["calor", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en LOS RIOS, QUEVEDO que ayuda a la comunidad en zonas de costa",
  },
  {
    id: "fundacion-do",
    name: "FUNDACIÓN DO",
    code: "145439",
    address: "Vía Latacunga",
    province: "COTOPAXI",
    city: "PUJILI",
    canton: "ZUMBAHUA",
    parroquia: "",
    institution: "Ministerio de Inc",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["sierra"],
    climateFocus: ["frio", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en COTOPAXI, PUJILI que ayuda a la comunidad en zonas de sierra",
  },
  {
    id: "fundacion-de",
    name: "FUNDACION DE",
    code: "145438",
    address: "Décima Tercera",
    province: "LOS RIOS",
    city: "QUEVEDO",
    canton: "QUEVEDO",
    parroquia: "",
    institution: "Ministerio de Inc",
    classification: "Fundaciones",
    status: "Registrada",
    regions: ["costa"],
    climateFocus: ["calor", "mixto"],
    targetGroups: ["niño", "adulto"],
    description:
      "Fundación registrada en LOS RIOS, QUEVEDO que ayuda a la comunidad en zonas de costa",
  },
];
